server:
    port: 9001
    # 统一接口访问前缀
    servlet-path: /hospHealth

#动态码
dynamic:
    #redis中的key标识
    codeKey:
        login: login
        register: register
        token: token
        updatePhone: updatePhone
    #有效时间
    effectiveTime:
        login: 300
        register: 300
        token: 31536000
        updatePhone: 300
    #下一次发送的时间
    nextSendTime:
        login: 60
        register: 60
        updatePhone: 60

token:
    #admin 用户token有效时间
    adminToken-effectiveTime: 31536000
    #用户 token有效时间 毫秒
    userToken-effectiveTime: 31536000
    #医生端 token有效时间 毫秒
    doctor-effectiveTime: 31536000

oss:
    accessKeyId: LTAIpXq9myrkBxUV
    accessKeySecret: sxg0punreq1ui7werfUQUfQ9RusIpo
    endpoint:
    bucketName:
    bucketUrl:

sms:
    region-id: cn-shenzhen
    access-key-id: 24766573
    access-key-secret: 7084a26058cadb98140bce2e0848dd72
    #短信API产品名称（短信产品名固定，无需修改）
    product: Dysmsapi
    #短信API产品域名（接口地址固定，无需修改）
    domain: dysmsapi.aliyuncs.com
    #短信签名
    name: 锦欣妇幼儿童保健医院

nginx:
    html-path: /docker/html
    new-html-prefix: http://182.92.78.118:9001/hospHealth/new

call-number:
    #排队叫号系统等待的队列
    waiting-que-name: call-number-waiting-que
    #排队叫号系统呼叫过的号码队列
    after-call-que-name: after-call-que

order:
    #需要关闭的订单队列
    clone-que: order-clone-que
    #异常支付订单队列
    exception-pay-que: exception-pay-que
    #未支付订单关闭时间(毫秒计算)
    close-time: 1800000
cron:
    send-close-order-time: 0 0/1 * * * ?
    clone-order-time: 0 0/1 * * * ?

#语言配置文件
language:
    fileName: languageCN.yml

#默认的
default:
    #用户头像
    userHeadPortrait: http://www.baidu.com
    #医生头像
    doctorHeadPortrait: http://www.163.com
    #默认的商品类别图片
    productTypeImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg
    #默认的商品图片
    productImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg
    #默认的商品sku图片
    skuImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg
    #用于生成金额校验key的秘钥
    checkSumKey: HUIBK33289H432BHVHJN432432

#开发环境
spring:
    datasource:
        beanPath: com.jinxin.hospHealth.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jinxin.hospHealth.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/misscheng?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root

redis:
    host: 119.29.108.150
    port: 6379
