server:
    port: 9001
    # 统一接口访问前缀
    servlet-path: /hospHealth

management:
    address: 127.0.0.1

#动态码
dynamic:
    #redis中的key标识
    codeKey:
        login: login
        register: register
        token: token
    #有效时间
    effectiveTime:
        login: 300
        register: 300
        token: 31536000

#默认的
default:
    #用户头像
    userHeadPortrait: http://www.baidu.com
    #医生头像
    doctorHeadPortrait: http://www.163.com
    #默认的商品类别图片
    productTypeImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg
    #默认的商品图片
    productImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg
    #默认的商品sku图片
    skuImage: http://yst.winshang.com/member/PinPai/2015/7/2/2015721650321136868_1.jpg

#开发环境
spring:
    profiles:
        active: dev
    datasource:
        beanPath: com.jinxin.hospHealth.dao.models
        mapperXmlPath: classpath:mapper/*.xml
        mapperPath: com.jinxin.hospHealth.dao.mapper
        master:
            name: ReadAndWrite
            url: jdbc:mysql://182.92.78.118:3306/misscheng?useUnicode=true&characterEncoding=utf-8&useSSL=false
            username: root
            password: root

redis:
    host: 119.29.108.150
    port: 6379
